- name: Play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play level variable
      ansible.builtin.debug:
        msg: Play level URL is {{URL}}

- name: File Level Variable
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print File level variable
      ansible.builtin.debug:
        msg: File level URL is {{URL}}

- name: Task Level Variable
  hosts: all
  tasks:
    - name: Print Task level Variable
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: Task level URL is {{URL}}

- name: Inventory Variable
  hosts: all
  tasks:
    - name: Print Task level Variable
      ansible.builtin.debug:
        msg: Inventory level URL is {{URL}}

- name: facts variable
  hosts: all
  tasks:
    - name: Print fact variable
      ansible.builtin.debug:
        msg: One of the fact variable is {{ansible_distribution}} and host ip is {{ansible_default_ipv4.address}}

- name: Register Variable
  hosts: all
  tasks:
    - name: Set Registered Variable
      ansible.builtin.shell: uptime
      register: out
    - name: Set fact variable
      ansible.builtin.set_fact:
        OUT: {{out.stdout}}
    - name: Print registered variable
      ansible.builtin.debug:
        msg: "{{out}}"
    - name: Print Fact variable
      ansible.builtin.debug:
        msg: {{OUT}}
