- name: Play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play level variable
      ansible.builtin.debug:
        msg: Play level URL is {{URL}}

- name: File Level Variable
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print File level variable
      ansible.builtin.debug:
        msg: File level URL is {{URL}}
