- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Download and unarchive Frontend
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Cleanup old content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Deploy frontend content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy roboshop conf
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/

- name: Restart nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: true
