- name: Install {{COMPONENT}} application
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejsapp.yml


#- name: Install NPM
#  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -
#
#- name: Install nodejs
#  ansible.builtin.yum:
#    name:
#      - nodejs
#      - gcc-c++
#    state: installed
#
#- name: Add application user
#  ansible.builtin.user:
#    name: roboshop
#    create_home: true
#
#- name: Cleanup old content
#  ansible.builtin.file:
#    path: /home/roboshop/catalogue
#    state: absent
#
#- name: Download and extract catalogue
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: download
#
#- name: Copy application
#  ansible.builtin.copy:
#    src: /tmp/catalogue-main/
#    dest: /home/roboshop/catalogue/
#    remote_src: yes
#  become_user: roboshop
#
#- name: Install catalogue app
#  community.general.npm:
#    path: /home/roboshop/catalogue/
#  become_user: roboshop
#
#- name: Copy systemd service file
#  ansible.builtin.copy:
#    src: systemd.service
#    dest: /etc/systemd/system/systemd.service
#
#- name: Start {{COMPONENT}} application
#  ansible.builtin.systemd:
#    name: catalogue
#    state: restarted
#    enabled: true
#    daemon_reload: true
